export enum KeyTypes {
    PBKDF2_KEY = 'PBKDF_KEYS',
    ECDH_PRIVATE_KEY = 'ECDH_PRIVATE_KEYS',
    ECDH_PUBLIC_KEY = 'ECDH_PUBLIC_KEYS',
    RSA_PRIVATE_KEY = 'RSA_PRIVATE_KEYS',
    RSA_PUBLIC_KEY = 'RSA_PUBLIC_KEYS',
    AES_KEY = 'AES_KEYS',
}